start_id: 651166
translate:
  apiKey: AQVNyVcSdLfJvhW8HMAz4WnX8ZQjS0yt1XaDN0a8
  folderId: b1g6d3iaj8fvksk5lu69
worker:
  seleniummode: 0
  seleniumPath: C:/Drivers/chromedriver.exe
  port: 9515
  pathToImage: C:/Users/Админ/Desktop/script/1.jpg
  processCount: 1
  login: Leaderq
  password: 12345QawDse
