start_id: 651173
translate:
  apiKey: AQVNyVcSdLfJvhW8HMAz4WnX8ZQjS0yt1XaDN0a8
  folderId: b1g6d3iaj8fvksk5lu69
worker:
  seleniummode: 1
  seleniumPath: /root/parser/src/remanga-worker/resources/chromedriver
  port: 9515
  pathToImage: /root/parser/src/remanga-worker/resources/1.jpg
  processCount: 1
  login: Leaderq
  password: 12345QawDse
